program: train.py
method: grid
parameters:
  lr:
    values: [0.01,0.001,0.0001,0.00001,0.000001]
  num_heads:
    values: [54,27,9,3,1] # [27,18,9,6,3,2,1] este debe ser un divisor de hidden_dim
  num_layers_1:
    values: [128,64,32,16,4,1] # [64,12,8,6,4,2,1]
  num_layers_2:
    values: [128,64,32,16,4,1] # [64,12,8,6,4,2,1] # self.transformer.decoder.num_layers
  dim_feedforward:
    values: [256,128,64,32,16,4,1] #
  #num_rows:
  #  values: [1] # [64,32,16,8,4,2,1] no importa losvalores porque solo usa 1 siempre
  #hidden_dim:
  #  values: [108] # RuntimeError: The size of tensor a (54) must match the size of tensor b (108) at non-singleton dimension 2