program: train.py
method: grid
parameters:
  sweep:
    values: [1]
  lr:
    values: [0.0001] #0.001, 0.00001,
  num_heads:
    values: [3] # [54,27,9,3,1] 27,18,9,6,3,2,1] este debe ser un divisor de hidden_dim
  num_layers_1:
    values: [9] # [64,12,8,6,4,2,1]
  num_layers_2:
    values: [3] # [128,64,32,16,4,,64,12,8,6,4,2,1] # self.transformer.decoder.num_layers
  dim_feedforward:
    values: [64,128] #
  device:
    values: [0]
  augmentation:
    values: [0]
    