program: train.py
method: grid
parameters:
  experiment_name:
    values: [Good+NoAug fold-5-seed-95-rtx6000]
  training_set_path:
    values: [
    "../SL_ConnectingPoints/split/DGI305-AEC--38--incremental--mediapipe_n_folds_5_seed_95_klod_1-Train.hdf5"]
  validation_set_path:
    values: [""]
  data_fold:
    values: [5]
  data_seed:
    values: [95]
  sweep:
    values: [1]
  lr:
    values: [0.0001] #0.001, 0.00001,
  num_heads:
    values: [2] # [54,27,9,3,1] 27,18,9,6,3,2,1] este debe ser un divisor de hidden_dim  : nhead
  num_layers_1:
    values: [3] # [64,12,8,6,4,2,1]
  num_layers_2:
    values: [2] # [64,12,8,6,4,2,1] # self.transformer.decoder.num_layers :n_clones
  dim_feedforward_encoder:
    values: [8]
  dim_feedforward_decoder:
    values: [16,64,32,8,512,1024,1280,256] #
  device:
    values: [1]
  augmentation:
    values: [0]
  factor_aug:
    values: [2]
  batch_name:
    values: [mean_1]
  batch_size:
    values: [64]
  loss_weighted_factor:
    values: [2]
  label_smoothing:
    values: [0.1]
  early_stopping_patience:
    values: [1000]
  epochs:
    values: [20000]
  scheduler:
    values: ["plateu"]
  optimizer:
    values: ['adam']
  weight_decay:
    values: [0.0001]
  weight_decay_dynamic:
    values: [0]
  dropout:
    values: [0.3]
  gaussian_std:
    values: [0.001]
  use_wandb:
    values: [1]
  hidden_dim:
    values : [108] # obligado 108 por tener 54*2 puntos

#python train.py --device=0 --dim_feedforward=128 --lr=0.0001 --num_heads=54 --num_layers_1=32 --num_layers_2=256 --sweep=1 --augmentation=1

#python train.py --augmentation=0 --batch_name=mean_1 --batch_size=64 --data_fold=5 --data_seed=1 --device=0 --dim_feedforward=8 --dropout=0.3 --early_stopping_patience=500 --epochs=1000 "--experiment_name=original +aug fold-5-seed-123-p100" --factor_aug=2 --gaussian_std=0.001 --label_smoothing=0.1 --loss_weighted_factor=2 --lr=0.0001 --num_heads=3 --num_layers_1=3 --num_layers_2=2 --optimizer=adam --scheduler=plateu --sweep=1 --training_set_path=../SL_ConnectingPoints/split/DGI305-AEC--38--incremental--mediapipe_n_folds_5_seed_123_klod_1-Train.hdf5 --use_wandb=0 --validation_set_path= --weight_decay=0.0001 --weight_decay_dynamic=1 --hidden_dim=108


#P100V100